# -*- coding: utf-8 -*-
"""LR_8_task_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ji51I6BvsHq1n9bmujscbN6VdCEo11_I
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install pyngrok==5.0.5
from pyngrok import ngrok

import cv2
from IPython.display import display, Javascript, HTML
from google.colab.output import eval_js
from base64 import b64decode
from google.colab.patches import cv2_imshow

# Функція для захоплення відео з вебкамери та відображення його в Colab
def webcam():
    js = Javascript('''
        async function create() {
            div = document.createElement('div');
            document.body.appendChild(div);

            video = document.createElement('video');
            video.setAttribute('playsinline', '');

            div.appendChild(video);

            stream = await navigator.mediaDevices.getUserMedia({video: {facingMode: "environment"}});
            video.srcObject = stream;

            await video.play();

            // Змінити розмір виводу для відповідності елементу відео.
            google.colab.output.setIframeHeight(document.documentElement.scrollHeight, true);

            return;
        }

        async function capture() {
            const canvas = document.createElement('canvas');
            canvas.width = video.videoWidth;
            canvas.height = video.videoHeight;
            canvas.getContext('2d').drawImage(video, 0, 0);
            img = canvas.toDataURL('image/jpeg', 0.8);
            return img;
        }
    ''')

    display(js)
    eval_js('create()')

    capturing = True

    # Захоплення зображення при натисканні 'q' або коли користувач вводить 'q' в текстовому полі
    display(HTML("Введіть 'q' у текстовому полі нижче, щоб припинити захоплення."))
    text_input = ""
    while capturing:
        img_data = eval_js('capture()')
        img_binary = b64decode(img_data.split(',')[1])

        # Зберегти зображення
        with open("DIACHENKO.jpg", "wb") as f:
            f.write(img_binary)

        # Перевірити, чи користувач ввів 'q' в текстовому полі
        if 'text_input' in locals() and text_input.lower() == 'q':
            capturing = False
        else:
            # Відображення текстового поля для введення користувачем
            text_input = input("Введіть 'q', щоб зупинити захоплення: ")

    # Звільнення вебкамери
    eval_js('stream.getTracks().forEach(track => track.stop());')

# OpenCV код для відображення захопленого зображення
webcam()

# Завантаження та відображення захопленого зображення
img = cv2.imread("DIACHENKO.jpg")
cv2_imshow(img)
cv2.waitKey(0)
cv2.destroyAllWindows()