# -*- coding: utf-8 -*-
"""LR_8_task_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nM6OkoC1RPxtUeA3HHXAMjUnbSRAx6Ta
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

img = cv2.imread("DIACHENKO.jpg")
kernel = np.ones((5,5),np.uint8)
imgGray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
imgBlur = cv2.GaussianBlur(imgGray,(7,7),0)
imgCanny = cv2.Canny(img,150,200)
imgDialation = cv2.dilate(imgCanny,kernel,iterations=1)
imgEroded = cv2.erode(imgDialation,kernel,iterations=1)

cv2_imshow(imgGray)
cv2_imshow(imgBlur)
cv2_imshow(imgCanny)
cv2_imshow(imgDialation)
cv2_imshow(imgEroded)