# -*- coding: utf-8 -*-
"""lr_2_task_3_example.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1II-HLqtASHrAt7quVF-ayZn9KAtKDy1z
"""

from sklearn.datasets import load_iris
iris_dataset = load_iris()

print("Ключі iris_dataset: \n{}".format(iris_dataset.keys()))

print(iris_dataset['DESCR'][:193] + "\n...")

print("Назви відповідей: {}".format(iris_dataset['target_names']))

print("Назва ознак: \n{}".format(iris_dataset['feature_names']))

print("Форма масиву data: {}".format(iris_dataset['data'].shape))

print("Тип масиву target: {}".format(type(iris_dataset['target'])))

print("Відповіді:\n{}".format(iris_dataset['target']))