# -*- coding: utf-8 -*-
"""LR_3_task_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WJmhxuvwA3EO8TPwuUtdlYRd77gB2cwN
"""

import numpy as np
from sklearn import linear_model
import sklearn.metrics as sm
from sklearn.preprocessing import PolynomialFeatures

# Завантаження даних з файлу
data = np.loadtxt('data_multivar_regr.txt', delimiter=',')

# Розбивка даних на навчальний та тестовий набори
X, y = data[:, :-1], data[:, -1]
num_training = int(0.8 * len(X))
X_train, y_train = X[:num_training], y[:num_training]
X_test, y_test = X[num_training:], y[num_training:]

# Створення та навчання моделі лінійної регресії
regressor = linear_model.LinearRegression()
regressor.fit(X_train, y_train)

# Прогноз результату для тестового набору даних
y_test_pred = regressor.predict(X_test)

# Виведення метрик якості лінійної регресії
print("Linear Regressor performance:")
print("Mean absolute error =", round(sm.mean_absolute_error(y_test, y_test_pred), 2))
print("Mean squared error =", round(sm.mean_squared_error(y_test, y_test_pred), 2))
print("Median absolute error =", round(sm.median_absolute_error(y_test, y_test_pred), 2))
print("Explained variance score =", round(sm.explained_variance_score(y_test, y_test_pred), 2))
print("R2 score =", round(sm.r2_score(y_test, y_test_pred), 2))

# Створення поліноміального регресора ступеня 10 та навчання його на тренувальних даних
polynomial = PolynomialFeatures(degree=10)
X_train_transformed = polynomial.fit_transform(X_train)

# Вибір вибіркової точки даних і створення поліноміального представлення
datapoint = [[7.75, 6.35, 5.56]]
poly_datapoint = polynomial.transform(datapoint)

# Створення об'єкта лінійного регресора та підгонка до полінома
poly_linear_model = linear_model.LinearRegression()
poly_linear_model.fit(X_train_transformed, y_train)

# Прогноз з використанням лінійного регресора та поліноміального регресора
linear_prediction = regressor.predict(datapoint)
poly_prediction = poly_linear_model.predict(poly_datapoint)

# Виведення результатів
print("Linear regression prediction:\n", linear_prediction)
print("Polynomial regression prediction:\n", poly_prediction)

# Порівняння результатів
print("\nComparison of predictions:")
print("Linear regression prediction is", linear_prediction - 41.35, "away from the actual value.")
print("Polynomial regression prediction is", poly_prediction - 41.35, "away from the actual value.")